# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ACSDKDemo' do
    pod 'ACSDK', :path => '../'
    pod 'PHFComposeBarView', '~> 2.0.2'
    pod 'SDWebImage'
end

